defaults: &defaults
  ftp_username: unixmen
  ftp_password: unixmen
  ftp_ip: 192.168.1.6
  # abdo's
  ftp_ip: localhost
  # ftp_root_dir: /srv/ftp
  ftp_root_dir: /srv/

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
